# Generated by Django 3.2.13 on 2022-11-12 16:55

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cafeType',
            field=models.CharField(choices=[('분위기가 좋은', '분위기가 좋은'), ('디저트가 맛있는', '디저트가 맛있는'), ('커피가 맛있는', '커피가 맛있는'), ('작업하기 좋은', '작업하기 좋은'), ('커피가 저렴한', '커피가 저렴한'), ('이색적인', '이색적인')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='menu',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
