# Generated by Django 3.2.13 on 2022-11-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_auto_20221113_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.PositiveBigIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
