# Generated by Django 3.2.13 on 2022-11-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
