# Generated by Django 3.2.13 on 2022-11-18 07:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_remove_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='images/cafe'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='images/cafe'),
        ),
    ]
