# Generated by Django 3.2.13 on 2022-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0006_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='parking',
            field=models.CharField(choices=[('분위기가 좋은', '분위기가 좋은'), ('디저트가 맛있는', '디저트가 맛있는')], max_length=20, null=True),
        ),
    ]
