# Generated by Django 3.2.13 on 2022-11-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roadname',
            field=models.CharField(default='판교역로', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sido',
            field=models.CharField(default='경기', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sigungu',
            field=models.CharField(default='성남시 분당구', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=80),
        ),
    ]
